version: "3"

services:
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    labels:
      traefik.enable: "true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./traefik/dev/static.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dev/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./certs:/etc/certs:ro
    networks:
      proxy:
        ipv4_address: 10.200.0.2

  ping:
    image: "traefik/whoami"
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`ping.docker.localhost`)
      - traefik.docker.network=proxy
      - "traefik.http.routers.whoami.tls=true"
    networks:
      proxy:
        ipv4_address: 10.200.0.3

networks:
  proxy:
    external: true
