version: "3"

services:
  traefik:
    container_name: "traefik"
    image: ghcr.io/dominx99/main-proxy
    command:
      - --providers.docker
      - --entrypoints.minecraft.address=:2565
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.traefik.service=api@internal"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - 2565:25565/tcp
      - "8880:8880"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./volumes/traefik/acme:/acme
      - ./volumes/traefik/logs:/logs
    networks:
      proxy:
        ipv4_address: 10.200.0.2

  ping:
    image: "traefik/whoami"
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`ping.chylo.pl`)
      - traefik.docker.network=proxy
    networks:
      proxy:
        ipv4_address: 10.200.0.3

networks:
  proxy:
    external: true
