version: "3"

services:
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    labels:
      traefik.enable: "true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./traefik/traefik-dev.yml:/etc/traefik/traefik.yml:ro
      - ./volumes/traefik/acme:/acme
      - ./volumes/traefik/logs:/logs
    networks:
      proxy:
        ipv4_address: 10.200.0.2

  ping:
    image: "traefik/whoami"
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`ping.chylo.local`)
      - traefik.docker.network=proxy
    networks:
      proxy:
        ipv4_address: 10.200.0.3

networks:
  proxy:
    external: true
