log:
  level: "DEBUG"
  filePath: "/logs/traefik.log"
providers:
  docker:
    exposedByDefault: false
    network: "proxy"
api:
  insecure: true
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
http:
  routers:
    traefik:
      rule: "Host(`proxy.chylo.local`,`dashboard.traefik.me`)"

certificatesResolvers:
  lets_encrypt_resolver:
    acme:
      email: "test@example.com"
      storage: "acme/acme.json"
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      tlsChallenge: true
