log:
  level: "DEBUG"
providers:
  docker:
    exposedByDefault: false
    network: "proxy"
api:
  insecure: true
entrypoints:
  web:
    address: ":443"
http:
  routers:
    traefik:
      rule: "Host(`proxy.chylo.local`,`dashboard.traefik.me`)"

certificatesResolvers:
  myresolver:
    acme:
      email: "test@example.com"
      storage: "/letsencrypt/acme.json"
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      tlsChallenge:
