log:
  level: DEBUG
  filePath: "/logs/traefik.log"

providers:
  docker:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
    watch: true

  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
  minecraft:
    address: ":2565"
  vault:
    address: ":8880"
