log:
  level: INFO
  filePath: "/logs/traefik.log"

providers:
  docker:
    exposedByDefault: false
    network: "proxy"

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
  minecraft:
    address: ":2565"
  vault:
    address: ":8880"

api:
  insecure: true
  dashboard: true

certificatesResolvers:
  lets_encrypt_resolver:
    acme:
      email: "dominx992@gmail.com"
      storage: "acme/acme.json"
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
