name: Deploy

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
jobs:
  my-instances:
    runs-on: ubuntu-latest
    name: Deploy application
    steps:
      -
        name: Checkout to current branch
        uses: actions/checkout@v3

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }} # github personal token

      - name: Import Secrets from self hosted vault
        uses: hashicorp/vault-action@v2
        with:
          url: http://vault.chylo.pl:8880
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/data/proxy/main DOMAIN | DOMAIN ;

      - name: Copy application environment to .env file
        run: 'envsubst < .env.tmpl > .env'

      -
        name: Build and push docker images
        uses: docker/bake-action@v2
        with:
          push: true
          files: 'docker-compose-prod.yml'
          targets: 'traefik'
          set: |
            traefik.platform=linux/arm64

      - name: Copy docker-compose to the OCI instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.INSTANCE_HOST }}
          key: ${{ secrets.INSTANCE_PRIVATE_KEY }} # ssh key
          username: opc
          source: "docker-compose-prod.yml,.env"
          target: "/home/opc/workspace/proxy/main/"

      - name: Start application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.INSTANCE_HOST }}
          key: ${{ secrets.INSTANCE_PRIVATE_KEY }} # ssh key
          username: opc
          script: |
            cd workspace/proxy/main
            mv docker-compose-prod.yml docker-compose.yml
            docker-compose pull
            docker-compose up -d
