name: Deploy

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
jobs:
  my-instances:
    runs-on: ubuntu-latest
    name: Deploy application
    steps:
      -
        name: Checkout to current branch
        uses: actions/checkout@v3

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Import Secrets from self hosted vault
        uses: hashicorp/vault-action@v2
        with:
          url: http://vault.chylo.pl:8880
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/data/proxy/main DOMAIN | DOMAIN ;

      - name: Copy application environment to .env file
        run: 'envsubst < .env.tmpl > .env'

      -
        name: Build and push docker images
        uses: docker/bake-action@v2
        with:
          push: true
          files: 'docker-compose-build.yml'
          targets: 'traefik'
          set: |
            traefik.platform=linux/amd64

      - name: Create project dir
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.INSTANCE_HOST }}
          key: ${{ secrets.INSTANCE_PRIVATE_KEY }}
          username: root
          script: |
            mkdir -p /root/workspace/proxy/main

      - name: Copy docker-compose to the instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.INSTANCE_HOST }}
          key: ${{ secrets.INSTANCE_PRIVATE_KEY }}
          username: root
          source: "docker-compose-prod.yml,.env"
          target: "/root/workspace/proxy/main/"

      - name: Start application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.INSTANCE_HOST }}
          key: ${{ secrets.INSTANCE_PRIVATE_KEY }}
          username: root
          script: |
            cd /root/workspace/proxy/main
            mv docker-compose-prod.yml docker-compose.yml
            docker-compose build --pull
            docker-compose up traefik --pull always -d --force-recreate

      - name: Create project dir for household
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOUSEHOLD_INSTANCE_HOST }}
          port: ${{ secrets.HOUSEHOLD_INSTANCE_PORT }}
          key: ${{ secrets.HOUSEHOLD_INSTANCE_PRIVATE_KEY }}
          proxy_port: ${{ secrets.HOUSEHOLD_INSTANCE_PORT }}
          username: root
          script: |
            mkdir -p /root/workspace/proxy/main

      - name: Copy docker-compose to the instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOUSEHOLD_INSTANCE_HOST }}
          port: ${{ secrets.HOUSEHOLD_INSTANCE_PORT }}
          key: ${{ secrets.HOUSEHOLD_INSTANCE_PRIVATE_KEY }}
          proxy_port: ${{ secrets.HOUSEHOLD_INSTANCE_PORT }}
          username: root
          source: "docker-compose-prod.yml,.env"
          target: "/root/workspace/proxy/main/"

      - name: Start application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOUSEHOLD_INSTANCE_HOST }}
          port: ${{ secrets.HOUSEHOLD_INSTANCE_PORT }}
          key: ${{ secrets.HOUSEHOLD_INSTANCE_PRIVATE_KEY }}
          proxy_port: ${{ secrets.HOUSEHOLD_INSTANCE_PORT }}
          username: root
          script: |
            cd /root/workspace/proxy/main
            mv docker-compose-prod.yml docker-compose.yml
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
            docker-compose build --pull
            docker-compose up traefik --pull always -d --force-recreate
